image: java:17-jdk

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export JAVA_HOME=/home/sdks/zulu-17

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .kotlin

build-linux:
  stage: build
  script:
    - ./gradlew 
      -DpublishDocs.root=/var/www/docs/multiplatform-jni 
      clean 
      publish 
      publishDocs 
      --no-daemon 
      --stacktrace
  only:
    - master
  tags:
    - linux

build-macos:
  stage: build
  script:
    - ./gradlew 
      clean
      publish{MacosX64,MacosArm64}PublicationToGitlabRepository
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - macos